selectFromResult for mutations
rtk-incubator/rtk-query pull request #206
Opened 2021-04-16 16:58 UTC by msutkowski

2021-04-17 16:17 UTC, markerikson approved these changes

2021-04-18 03:58 UTC, msutkowski reviewed
This change will require updates in the docs that were merged: https://github.com/rtk-incubator/rtk-query/pull/191/files#diff-b2cf37354c870ebf35a4045446fae1006ca83193784282bb2066da6bba8a1f91R94, but was introduced for consistency with the other hook names

2021-04-18 15:44 UTC, phryneas requested changes
Already said it in chat - I think we don't need the fancy type overloading here as we don't really have a use for `isFetching` in mutations.

My change suggestions might be a bit sloppy, I'm not feeling so well :upside_down_face:

2021-04-18 15:44 UTC, phryneas commented on src/react-hooks/buildHooks.ts
> +      );
```suggestion
      const currentState = useSelector(mutationSelector, shallowEqual);
```

2021-04-18 15:44 UTC, phryneas commented on src/react-hooks/buildHooks.ts
> +) => UseMutationStateDefaultResult<D>;
```suggestion
) => MutationResultSelectorResult<D>;
```

2021-04-18 15:44 UTC, phryneas commented on src/react-hooks/buildHooks.ts
> +>;
```suggestion
```

2021-04-18 15:44 UTC, phryneas commented on src/react-hooks/buildHooks.ts
> +export type UseMutation<D extends MutationDefinition<any, any, any, any>> = <R = UseMutationStateDefaultResult<D>>(
```suggestion
export type UseMutation<D extends MutationDefinition<any, any, any, any>> = <R = MutationResultSelectorResult<D>>(
```

2021-04-18 15:44 UTC, phryneas commented on src/react-hooks/buildHooks.ts
> +  return currentState as UseMutationStateDefaultResult<any>;
```suggestion
  return currentState;
```

2021-04-18 15:44 UTC, phryneas commented on test/buildHooks.test.tsx
> +    it('does not cause a rerender when using selectFromResult with an empty object', async () => {
```suggestion
    it('causes no more than one rerender when using selectFromResult with an empty object', async () => {
```

2021-04-18 16:56 UTC, msutkowski commented on src/core/apiState.ts
> +    } & BaseMutationSubState<D>) & { data?: undefined })
Forces the return type of `result.data` from `string | undefined` to `undefined` in the unionTypes test, which is what we want. `data` should never be a string there as a new request is `{ isLoading: true, data: undefined, error: undefined `

2021-04-18 21:11 UTC, phryneas requested changes
mini nitpicks, then this can go in :)

2021-04-18 21:11 UTC, phryneas commented on src/core/buildSelectors.ts
>  ) => (state: RootState) => MutationSubState<Definition> & RequestStatusFlags;
```suggestion
) => (state: RootState) => MutationResultSelectorResult<Definition>;
```

2021-04-18 21:11 UTC, phryneas commented on src/react-hooks/buildHooks.ts
> +};
```suggestion
const defaultMutationStateSelector: DefaultMutationStateSelector<any> = (currentState) => currentState;
```

2021-04-18 21:31 UTC, merged