Lazy loading & hot reloading: allow to inject & override api defintions on existing api
rtk-incubator/rtk-query pull request #24
Opened 2020-11-13 16:59 UTC by phryneas

2020-11-13 17:16 UTC, msutkowski commented on examples/svelte/src/App.svelte
> +    $: ({ data } = counterApi.selectors.getCount()($store));
```suggestion
    $: ({ data } = selectors.getCount()($store));
```

2020-11-13 17:16 UTC, msutkowski commented on src/buildActionMaps.ts
> +      return buildMutationAction(endpoint, definition);
Readability wins 🏆

2020-11-13 17:59 UTC, markerikson commented
yayyyy!

2020-11-14 20:53 UTC, phryneas commented on src/index.ts
> +  return api.injectEndpoints({ endpoints });
it's so :fire:  that this works

2020-11-14 23:49 UTC, phryneas commented
Aaaand it's done. The API changed a bit and now has this shape:
```ts
export interface Api<
  InternalQueryArgs,
  Definitions extends EndpointDefinitions,
  ReducerPath extends string,
  EntityTypes extends string
> {
  reducerPath: ReducerPath;
  actions: EndpointActions<Definitions>;
  internalActions: SliceActions;
  reducer: Reducer<CombinedState<Definitions, EntityTypes> & QueryStatePhantomType<ReducerPath>, AnyAction>;
  selectors: Selectors<Definitions, RootState<Definitions, EntityTypes, ReducerPath>>;
  middleware: Middleware<{}, RootState<Definitions, string, ReducerPath>, ThunkDispatch<any, any, AnyAction>>;
  hooks: Hooks<Definitions>;
  injectEndpoints<NewDefinitions extends EndpointDefinitions>(_: {
    endpoints: (build: EndpointBuilder<InternalQueryArgs, EntityTypes>) => NewDefinitions;
    overrideExisting?: boolean;
  }): Api<InternalQueryArgs, Definitions & NewDefinitions, ReducerPath, EntityTypes>;
}
```

Also, there's the new `ApiWithInjectedEndpoints` type - we can still rename that if someone has a better idea.

2020-11-15 00:01 UTC, msutkowski requested changes

2020-11-15 00:01 UTC, msutkowski commented on examples/react/src/features/bundleSplitting/Post.tsx
> +  return !data ? <>loading</> : <h1>{data.name}</h1>;
```suggestion
  return error ? <>there was an error</> : !data ? <>loading</> : <h1>{data.name}</h1>;
```

2020-11-15 00:01 UTC, msutkowski commented on examples/react/src/features/bundleSplitting/PostsList.tsx
> +  return !data ? (
```suggestion
  return error ? <>there was an error</> : !data ? (
```

2020-11-15 00:01 UTC, msutkowski commented on examples/react/src/features/bundleSplitting/PostsList.tsx
> +  const { data } = apiWithPosts.hooks.getPosts.useQuery();
```suggestion
  const { data, error } = apiWithPosts.hooks.getPosts.useQuery();
```

2020-11-15 00:01 UTC, msutkowski commented on examples/react/src/features/bundleSplitting/Post.tsx
> +  const { data } = splitApi.hooks.getPost.useQuery(id);
```suggestion
  const { data, error } = splitApi.hooks.getPost.useQuery(id);
```

2020-11-15 16:29 UTC, merged